spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'ccnuPass@67867024'
    url: jdbc:mysql://localhost/bbs?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  ##redis配置，默认密码为空
  redis:
    host: localhost
    # Redis服务器连接端口
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
#    password: 'ccnuPass@67867024'
  #  json格式化
  jackson:
    default-property-inclusion: non_null
#微信小程序配置
wechat:
  appId: wxf2e2bcf3a3a02033
  appSecret: cd33a6180d27b3d8cfab55333d068bb8
#七牛云配置
qiniu:
  accessKey: xCz0OKEZj4Xz0cWyF-pKwxgL8qLAeJwgDqOZTp3c
  secretKey: 2rw9fk61IK5J2jpB52E1coG8wrjjQcYywkA5G4u8
  bucket: image
  path: http://img.ccnunercel.cn
server:
  servlet:
    context-path: /bbs
  port: 80
